# Generated by Django 4.2.5 on 2023-09-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appname', '0002_rename_content_blog_description_remove_blog_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
